on:
  push:
    branches:
      - main
      - master

name: test-data

jobs:
  test-data:
    runs-on: ubuntu-latest
    env:
      working-directory: ./test/
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('formattable')
          install.packages('yaml')
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-


      - name: Test data
        run: rmarkdown::render('tools/summary.Rmd', params = list(folder = 'CMU-DS'), output_file = 'Data/CMU-DS/CMU-DS-summary.html')
        shell: Rscript {0}

