name: Create Summary Workflow
on: [push]

jobs:
  Create-Summmary-Job: 
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.CODECOV_TOKEN }}
      # don't treat missing suggested packages as error
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      # - name: Query dependencies
      #   run: |
      #     install.packages('remotes', repos='https://mirrors.ustc.edu.cn/CRAN/')
      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
      #     writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      #   shell: Rscript {0}

      # - name: Cache R packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
      #     restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages('remotes', repos='https://mirrors.ustc.edu.cn/CRAN/')
          remotes::install_deps(dependencies = TRUE)
          install.packages('rmarkdown', repos='https://mirrors.ustc.edu.cn/CRAN/')
        shell: Rscript {0}
      - name: summary rmd
        run: Rscript -e "rmarkdown::render('tools/summary.Rmd', output_file = 'Data/CMU-DS/CMU-DS-summary.html')" CMU-DS
        id: body
      - name: summary output
        run: echo 'The time was ${{ steps.body.outputs.time }}.'

